import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getAccessTokenFromStorage } from "@/lib/storage/authStorage";

import AuthenticatedNavbar from "@/components/layout/AuthenticatedNavbar";
import AuthenticatedFooter from "@/components/layout/AuthenticatedFooter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = getAccessTokenFromStorage();
  const isAuthenticated = !!token;
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthenticatedNavbar />
        {children}
        <AuthenticatedFooter />
      </body>
    </html>
  );
}
